### ISSUE TITLE
Feature: Add additional volumes to deployment template with configmaps or secrets

### ISSUE THREAD

**Issue by jmspradlin** [saucelabs/helm-charts#18]
## Expected Behavior
The ability to specify additional secrets or config maps as volumes and mounts is present, along with preset volume mounts, within the Helm chart.

## Actual Behavior
Only the pre-defined volume mount for `config-volume` is present in the Deployment.yaml template.

## Suggested Feature
deployment.yaml
```
spec:
  template:
    spec:
      volumes:
        - name: config-volume
          configMap:
            name: {{ include "sauce-connect.fullname" . }}
      {{- range .Values.query.extraConfigmapMounts }}
        - name: {{ .name }}
          configMap:
            name: {{ .configMap }}
      {{- end }}
      {{- range .Values.query.extraSecretMounts }}
        - name: {{ .name }}
          secret:
            secretName: {{ .secretName }}
      {{- end }}
...
      volumeMounts:
        - name: config-volume
          mountPath: /etc/config
      {{- range .Values.query.extraSecretMounts }}
        - name: {{ .name }}
          mountPath: {{ .mountPath }}
          subPath: {{ .subPath }}
          readOnly: {{ .readOnly }}
      {{- end }}
      {{- range .Values.query.extraConfigmapMounts }}
        - name: {{ .name }}
          mountPath: {{ .mountPath }}
          subPath: {{ .subPath }}
          readOnly: {{ .readOnly }}
      {{- end }}
```
